### ISSUE TITLE
alert support request and status use case

### ISSUE THREAD

**Issue by victormakmo** [BTplc/grafana-trend-dot#2]
hello,
Since Grafana 4 added e-mail alert support. it is a great feature and i hope trend-dot also support.

And i find that the trend-dot run on grafana 4 threshold units only allow "%". But i don't know how the percent calculated. Below is my use case, i only want my value greater than 10, the dot will change to red. but i don't what exactly 1000% means. please clarify. Thanks.

![image](https://cloud.githubusercontent.com/assets/25501819/22543628/66812622-e96c-11e6-9acc-8a40541f6c11.png)

![image](https://cloud.githubusercontent.com/assets/25501819/22543658/8df5d54a-e96c-11e6-87cd-fbb98664bdd6.png)

**Comment by benthorner** [comment]
Hi Victor. Sorry we didn't get back to you sooner. This plugin is now deprecated. We've created a new one, which may be more suitable for your needs: https://github.com/BTplc/grafana-status-dot. If you're still having issues, feel free to open a new one.
